POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "hakuna matata",
    "author": "Simba",
    "url": "idk",
    "likes": "2"
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "heippis!",
    "author": "Taikuri Luttinen",
    "url": "emt",
    "likes": 1
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJydWgiLCJpZCI6IjY3NGQ4MDNjMWJhMWRlYjU2ZGJlYzQ2NiIsImlhdCI6MTczMzIzNTQzMn0.uWTsBvcXYsyq55iM4M_qyMrw455e7TrmLmSuI-fz8fo
{
    "title": "jauzaa",
    "author": "Luikuri Tattinen",
    "url": "evvk",
    "likes": 3
}
