POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "hakuna matata",
    "author": "Simba",
    "url": "idk",
    "likes": "2"
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "heippis!",
    "author": "Taikuri Luttinen",
    "url": "emt",
    "likes": 1
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJydWgiLCJpZCI6IjY3NGQ4MDNjMWJhMWRlYjU2ZGJlYzQ2NiIsImlhdCI6MTczMzIzMTYzNH0.3R5gUQqqgHJjWLVBKnMeh7Emm-9OQ14O3T_cSZYpiTQ
{
    "title": "jauzaa",
    "author": "Luikuri Tattinen",
    "url": "evvk",
    "likes": 3
}
