POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "hakuna matata",
    "author": "Simba",
    "url": "idk",
    "likes": "2"
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "heippis!",
    "author": "Taikuri Luttinen",
    "url": "emt",
    "likes": 1
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 
{
    "title": "jauzaa",
    "author": "Luikuri Tattinen",
    "url": "evvk",
    "likes": 3
}
